services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    restart: unless-stopped
    volumes:
      - ./web:/var/www/html

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: VaccineLab
      MARIADB_USER: lab
      MARIADB_PASSWORD: lab
    ports:
      - "3306:3306"
    volumes:
      - ./db/init-mariadb.sql:/docker-entrypoint-initdb.d/database.sql:ro
      - db_data:/var/lib/mysql

volumes:
  db_data:
